#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm test || (
        echo '😆 Please redo you testing 😆'
        false; 
)
npm run lint || (
  echo '💢 Please fix your lint before doing commits 💢'
  false;
)
